export const siteConfig = {
  name: "SulitScan PH",
  shortName: "SulitScan",
  tagline: "Curated online deals and shopping guides for Filipino shoppers.",
  description:
    "SulitScan PH helps Filipino shoppers find curated online deals with honest buyer notes, fake-discount checks, and smart shopping guides for Temu, Shopee PH, and Sephora PH.",
  url: "https://sulitscan.com",
  ogImage: "https://sulitscan.com/og-image.jpg",
  locale: "en_PH",
  twitterHandle: "@sulitscanph",
}

export const defaultMetadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: "SulitScan PH | Curated Online Deals and Shopping Guides for Filipino Shoppers",
    template: "%s | SulitScan PH",
  },
  description: siteConfig.description,
  keywords: [
    "online deals Philippines",
    "discount products Philippines",
    "Filipino shopping guide",
    "Temu deals Philippines",
    "Temu Philippines shopping guide",
    "Temu finds Philippines",
    "Shopee PH deals",
    "Shopee finds Philippines",
    "Shopee under 500 Philippines",
    "Sephora PH deals",
    "Sephora Philippines sale",
    "beauty deals Philippines",
    "skincare deals Philippines",
    "budget finds Philippines",
    "sulit finds",
    "affiliate deals Philippines",
    "Filipino shopper guide",
    "Temu gadgets Philippines",
    "Sephora beauty deals Philippines",
    "home finds Philippines",
    "under 500 Philippines deals",
  ],
  authors: [{ name: "SulitScan PH", url: siteConfig.url }],
  creator: "SulitScan PH",
  publisher: "SulitScan PH",
  openGraph: {
    type: "website" as const,
    locale: siteConfig.locale,
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: "SulitScan PH | Curated Online Deals and Shopping Guides for Filipino Shoppers",
    description: siteConfig.description,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: "SulitScan PH – Check deals before you click buy",
      },
    ],
  },
  twitter: {
    card: "summary_large_image" as const,
    title: "SulitScan PH | Curated Online Deals and Shopping Guides for Filipino Shoppers",
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: siteConfig.twitterHandle,
    site: siteConfig.twitterHandle,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large" as const,
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: siteConfig.url,
  },
}
